SPEC.md

Hello!
@adrianchiris you mentioned the following error:
> failure to apply any configuration specified in containerSpec by the runtime (devices, mounts, hooks)
Can you detail a bit more your thoughts?
Thanks!
Signed-off-by: Renaud Gaubert <rgaubert@nvidia.com>

Add new failure scenarios

---

.github/workflows/sanity.yml
go.mod
go.sum
pkg/devices.go
pkg/devices_test.go
specs-go/config.go
specs-go/oci.go

This Pull Request adds the initial code for CDI, we should then be able to import cdi/pkg from other projects with the following two functions:
- HasDevice -> Check if a Device given by a user is a CDI device
- UpdateOCISpecForDevices -> Update the OCI spec for a set of CDI device
This is missing tests for UpdateOCISpecForDevices but it's a first start.
This should also probably be optimized to cache the different files but these may come as a followup PR

Add inital CDI code

---

specs-go/oci.go

Appended environment variables from
CDI ociEdits.Env to the runtime spec Process.Env
Fixes: #20

handle ociEdits.Env

---

README.md
SPEC.md
schema/defs.json
schema/testdata/good/minimal.json
schema/testdata/good/spec-example.json
specs-go/config.go
specs-go/oci.go
specs-go/oci_test.go

Added type, major, minor, uid and gid properties to the DeviceNode definition.
Property types were taken from the [OCI LinuxDevice](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/specs-go/config.go#L377:L393).
Fixes: #26, #17

extend DeviceNode definition

---

specs-go/oci.go

This change removes an unused toOCIDevice function that was converting a
CDI Device node to an OCI Mount. This is no longer required as the CDI devices
are now represented as OCI Linux Devices.
Signed-off-by: Evan Lezar <elezar@nvidia.com>

Remove unused toOCIDevice function

---

pkg/devices_test.go
specs-go/config.go
specs-go/oci_test.go

This change renames the type specs.Devices to specs.Device as the intent
is to represent a single device. This improves the redability of the
Devices slice which how has the type []Device and not []Devices.
Signed-off-by: Evan Lezar <elezar@nvidia.com>

Rename specs.Devices to specs.Device

---

README.md
schema/defs.json
schema/schema.json
schema/testdata/good/minimal.json
schema/testdata/good/spec-example.json
specs-go/config.go

Sync Spec implementation and schema:
- update DeviceNode.Permissions to be a string
- change ociEdits in the schema to containerEdits
- update schema validation tests
Additionally, fix a bunch of thinkos and typos in the sample JSON CDI Spec:
- field name without leading quote ('type":')
- old field names ("ociEdits" vs. "containerEdits")
- a few missing and extra commas

specs: sync Spec implementation and schema.

---

pkg/devices.go
pkg/devices_test.go

Align `UpdateOCISpecForDevicesWithSpec()` with `collectCDISpecs()`. The latter uses `extractVendor()`ed devices names to look up `CDI Specs`. Consequently the former must do the same when updating `OCI Spec`s with the collected CDI ones. Otherwise the update will fail for fully qualified CDI device names (ones which are of the form `vendor/type=name`).
While at it, also fix the incorrect doc-string for the same function and add a minimal set of test cases for it.

pkg/devices: fix UpdateOCISpecForDevicesWithSpec.

---

CONTRIBUTING.md

Signed-off-by: Evan Lezar <elezar@nvidia.com>

Add PR guidelines to CONTRIBUTING

---

SPEC.md
schema/schema.json
specs-go/config.go

Remove unused Spec.KindShort and Device.NameShort, as agreed in the last COD gathering.

specs-go, schema: remove KindShort and NameShort.

---

README.md
SPEC.md
pkg/cdi/cache_test.go
pkg/cdi/registry_test.go
pkg/cdi/spec-dirs_test.go
pkg/cdi/spec.go
pkg/cdi/spec_test.go
pkg/devices_test.go
schema/schema.json
schema/testdata/good/minimal.json
schema/testdata/good/spec-example.json
specs-go/config.go
specs-go/oci_test.go

This set of changes prepares for the v0.3.0 spec release. The changes include:
* Adding a `CurrentVersion` const to the spec definition
* Removing the unused `ContainerRuntimes` field from the spec
* Updating all version references to 0.3.0 (from `0.2.0` or `0.1.0`)

Prepare for v0.3.0 Spec release

---

go.mod
go.sum

Requiring v1.10.0 break CRI-O OpenShift CI e2e tests.
While the exact details are not fully understood, this
dependency was identified as the culprit for breakage,
by manually bisecting commits and rerunning CI tests.
The problem manifests itself by failing to bootstrap
the cluster with multus-related timeouts or errors.
While this is a PITA, current CRI-O codebase depends
on opencontainers/selinux v1.9.1, and Kubernetes on
v1.8.2. We presumably can safely update the dependency
once those move forward.
Signed-off-by: Krisztian Litkey <krisztian.litkey@intel.com>

go.{mod,sum}: relax selinux requirement to v1.9.1.

---

pkg/cdi/spec.go
pkg/cdi/spec_test.go

Unmarshalling empty Spec data results in the raw Spec pointer set to nil. Handle this gracefully instead of crashing on it by recording a Spec-specific error indicating the lack of valid Spec data.

pkg/cdi: handle unmarshalling empty Spec data.

---

schema/defs.json

Spec mount options should be an array of strings not a string.

schema: fix Mount.Options in schema.

---

README.md
SPEC.md
pkg/cdi/spec.go
pkg/cdi/spec_test.go
schema/defs.json
schema/testdata/good/spec-example.json
specs-go/config.go
specs-go/oci.go

This change adds a Type field for mounts that allows for the specification of, for example, `tmpfs` mounts.
See https://github.com/opencontainers/runtime-spec/blob/main/config.md#posix-platform-mounts
Closes #45

[spec] Add type field for mounts

---

pkg/cdi/spec-dirs.go
pkg/cdi/spec-dirs_test.go

Ignore scanning errors related to missing Spec directories. This should fix errors where a missing directory (typically /etc/cdi) prevents the resolution of devices using files from subsequent configured directories. Fixes #78 .

pkg/cdi: don't abort scan on missing Spec dir.

---

Makefile
pkg/cdi/cache.go
pkg/cdi/regressions_test.go

When being (re)configured, do not delay dereferencing our fsnotify.Watcher into the start()/watch() goroutine. That is not protected by the lock in Configure() and can trigger a read/write data race. Instead, dereference it while being properly locked and pass it as an argument to watch().
Fixes #81 which should fix [this containerd PR](https://github.com/containerd/containerd/pull/7331) once this fix gets tagged and that containerd PR is updated to use the fix.
This PR also adds a regression test with a gutted version of the containerd test case that triggered this bug.

Fix a read/write data race in the cache.

---

.github/workflows/sanity.yml
pkg/cdi/cache_test.go
pkg/cdi/cache_test_unix.go
pkg/cdi/cache_test_windows.go
pkg/cdi/container-edits.go
pkg/cdi/container-edits_unix.go
pkg/cdi/container-edits_windows.go
pkg/cdi/spec.go

Fix two build failures for Windows. One in stock code and another in tests, which show up as a 'go vet' failure. Fix a data read/write race which was probably triggered by the latter Windows fix slightly altering timing in some of tests... or just by sheer luck.
Update the github workflow to run sanity checking (lint, vet) both *for* Linux and Windows. The checks always run *on* a Linux distro, but they override GOOS/GOARCH for the toolchain.
Update the github worfklow to do binary test builds/cross-builds both for Linux and Windows.

pkg/cdi: fix build/vet failures on windows.

---

pkg/cdi/cache.go
pkg/cdi/cache_test.go
pkg/cdi/doc.go
pkg/cdi/registry.go
pkg/cdi/spec.go
pkg/cdi/spec_test.go

Add convenience functions for generating Spec names for ordinary and transient Spec files. The generated names can be passed to WriteSpec() of Cache or Registry to atomically write a Spec file. Also add a function for removing Spec files created with WriteSpec().

pkg/cdi: add functions for generating Spec names and removing Spec files.

---

go.mod
internal/multierror/multierror.go
internal/multierror/multierror_test.go
pkg/cdi/cache.go
schema/schema.go

The internal replacement is a simpler implementation which only supports enough functionality for the places where github.com/hashicorp/go-multierror was used before.
Not depending on github.com/hashicorp/go-multierror and thus github.com/hashicorp/errwrap makes it easier to use CDI in Kubernetes because we don't need to add those other dependencies.
Fixes: #88

remove usage of github.com/hashicorp/go-multierror

---

pkg/cdi/cache.go

Avoid a read/write data race between refresh() and GetSpecErrors() by taking the cache lock during GetSpecErrors(). While at it, also make a copy and return that instead of the original error slice in the Spec.
Signed-off-by: Krisztian Litkey <krisztian.litkey@intel.com>

pkg/cdi: fix GetSpecErrors()/refresh read/write data race.

---

go.mod
go.sum

The update runtime-tools contain
https://github.com/opencontainers/runtime-tools/pull/755 and thus CDI will have less dependencies when only used to write files without validation.
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>

dependencies: update opencontainers packages (rebased #87)

---

pkg/cdi/doc.go

Signed-off-by: Moshe Levi <moshele@nvidia.com>

fix cdi doc missing SpecDB()

---

cmd/cdi/cmd/cdi-api.go
cmd/cdi/cmd/inject.go
cmd/cdi/cmd/monitor.go
go.mod
go.sum
pkg/cdi/annotations.go
pkg/cdi/cache.go
pkg/cdi/cache_test.go
pkg/cdi/container-edits.go
pkg/cdi/container-edits_unix.go
pkg/cdi/device.go
pkg/cdi/doc.go
pkg/cdi/qualified-device.go
pkg/cdi/spec-dirs_test.go
pkg/cdi/spec.go
pkg/cdi/spec_linux.go
pkg/cdi/spec_test.go
schema/schema.go

Get rid of `github.com/pkg/errors` dependency.

cmd, pkg, schema: stop using github.com/pkg/errors.

---

Makefile
cmd/cdi/go.mod
cmd/cdi/go.sum
go.mod

Turn 'cdi' test binary into a go module of its own. This should prevent dependencies specific to that binary from leaking into any CDI downstream dependencies.

cmd/cdi: split out to a go module of its own.

---

.github/dependabot.yml

The dependabot PRs created fail due to a missing label.
This PR removes the setting.
An alternative would be to add the label to the project.
See for example: https://github.com/container-orchestrated-devices/container-device-interface/pull/124#issuecomment-1469927721

Removed release-note-none label from dependabot

---

pkg/cdi/spec.go

This includes a YAML separator (`---`) at the start of the YAML output which makes working with multiple spec files simpler.
Closes #111

Prepend yaml separator (---) to yaml output

---

.github/dependabot.yml
go.mod
go.sum

This field is required due to the `ignore` changes added in #125.

Add required dependency-name field to dependabot config

---

pkg/cdi/annotations.go
pkg/cdi/device.go
pkg/cdi/qualified-device.go
pkg/cdi/registry.go
pkg/cdi/spec_test.go
pkg/cdi/version.go
pkg/parser/parser.go
pkg/parser/parser_test.go

This should allow golang dependencies to be better managed.
See https://github.com/docker/cli/pull/4084#pullrequestreview-1351095415

Move parsing and name validation to cdi/parse package

---

SPEC.md
pkg/cdi/qualified-device.go
pkg/cdi/qualified-device_test.go
pkg/cdi/spec_test.go
pkg/cdi/version.go
pkg/parser/parser.go
pkg/parser/parser_test.go

CDI spec states that dots ('.') are allowed.
Add support in parser for this.
reference: https://github.com/container-orchestrated-devices/container-device-interface/blob/main/SPEC.md#kind

Support dots in Kind name segment

---

.codespellrc
.github/workflows/codespell.yml
README.md
SPEC.md
cmd/cdi/cmd/resolve.go
pkg/cdi/annotations.go
pkg/cdi/container-edits.go
pkg/cdi/doc.go
pkg/cdi/qualified-device.go
pkg/cdi/spec.go
pkg/cdi/version.go
pkg/parser/parser.go
specs-go/oci.go

While listening to @elezar  giving a presentation, decided to check the CDI out: Having typos free code would be very useful for 1.0 release ;)

codespell: workflow, config, typos fixed

---

.github/workflows/sanity.yml
pkg/cdi/cache.go
pkg/cdi/cache_test.go

In `InjectDevices()` we are currently error-logging the whole list of devices instead of the device handles which weren't resolved

log the unresolved CDI devices only

---

SECURITY.md
code-of-conduct.md

This change adds files as required for [moving the repo to cncf-tags](https://github.com/cncf/toc/blob/main/tags/cncf-tags-github-org.md#mandatory-files).
This adds:
* A `code-of-conduct.md` referencing the CNCF Code of Conduct
* An empty Security Policy

Add cncf tags required files

---

cmd/cdi/cmd/validate.go

Print out any errors encountered during validation, as suggested by the command help.

cmd/validate: print the validation errors

---

cmd/cdi/go.mod
cmd/validate/go.mod
go.mod
go.sum
specs-go/go.mod
specs-go/go.sum

This should allow to import CDI spec structures without adding a lot of CDI runtime deps.
It should partly fix #97  and allow Kubernetes to refer this module directly. There are at least 2 places in the k/k codebase that would benefit from this change:
- this can be replaced by the specs-go import: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/dra/test-driver/app/cdi.go
- this can import specs-go and use JSON marshalling instead of quite ugly approach it uses to write CDI files: https://github.com/kubernetes/kubernetes/blob/master/test/images/sample-device-plugin/sampledeviceplugin.go#L237

make specs-go a module

---

cmd/cdi/go.mod
go.mod

This change adds a v0.6.0 version to the internal specs-go dependency. This prevents a transitive dependency on the v0.0.0-00010101000000-000000000000 pseudo version when importing the package into clients.

Add version to spec-go dependency

---

README.md
cmd/cdi/cmd/cdi-api.go
cmd/cdi/cmd/monitor.go
cmd/cdi/cmd/root.go
cmd/cdi/cmd/specs.go
cmd/cdi/cmd/validate.go
cmd/cdi/go.mod
cmd/cdi/main.go
cmd/validate/go.mod
cmd/validate/validate.go
go.mod
internal/validation/k8s/objectmeta.go
internal/validation/validate.go
pkg/cdi/annotations.go
pkg/cdi/cache.go
pkg/cdi/cache_test.go
pkg/cdi/container-edits.go
pkg/cdi/container-edits_test.go
pkg/cdi/device.go
pkg/cdi/device_test.go
pkg/cdi/doc.go
pkg/cdi/qualified-device.go
pkg/cdi/registry.go
pkg/cdi/spec.go
pkg/cdi/spec_test.go
pkg/cdi/validate/schema.go
pkg/cdi/version.go
schema/schema.go
schema/schema_test.go
specs-go/go.mod

With https://github.com/cncf/toc/issues/1152 addressed, we are able to use the `tags.cncf.io` vanity URL in our module names.

Use tags.cncf.io URL in module names

---

.codespellrc
SPEC.md
pkg/cdi/container-edits.go
pkg/cdi/container-edits_test.go
pkg/cdi/spec_test.go
pkg/cdi/version.go
schema/defs.json
specs-go/config.go
specs-go/oci.go

Add support for specifying the OCI Linux.IntelRdt configuration that is the control point for cache and memory bandwidth allocation technologies sucn as Intel RDT (Resource Director Technology). There can only be one IntelRdt configuration per container so in case multiple specs happened to specify it the last one applied prevails. Also, the IntelRdt configuration is always applied as a whole - editing specific sub-fields is not supported.

Add IntelRdt to CDI spec

---

cmd/cdi/cmd/inject.go
cmd/validate/validate.go
pkg/cdi/spec-dirs_test.go
pkg/cdi/spec.go
pkg/cdi/spec_test.go
schema/schema.go
schema/schema_test.go

Replace with corresponding functions from io and os packages.

chore: stop using deprecated io/ioutil package

---

SPEC.md
pkg/cdi/container-edits.go
pkg/cdi/container-edits_test.go
pkg/cdi/spec_test.go
pkg/cdi/version.go
schema/defs.json
specs-go/config.go

This change adds an AdditionalGIDs field to the ContainerEdits structure. This allows CDI spec producers to associate a group ID with the container's user to allow access to, for example, device nodes with specific permissions.
This closes #175

Add AdditionalGIDs field to ContainerEdits

---

pkg/cdi/registry.go

chore: omit error checking more explicitly

---

pkg/cdi/cache.go
pkg/cdi/spec-dirs.go

Options never fail so why return an error.

chore: simplify cache Option type

---

cmd/cdi/cmd/cdi-api.go
pkg/cdi/cache.go
pkg/cdi/cache_test.go
pkg/cdi/registry.go

Drop the unused (always nil) error returned by NewCache(). This eliminate some unreachable error paths in the code.
> **NOTE:** This change changes the exported API of "pkg/cdi" package as the prototype of NewCache() changes.

pkg/cdi: drop unused return value from NewCache function

---

cmd/cdi/cmd/cdi-api.go
pkg/cdi/cache.go
pkg/cdi/cache_test.go
pkg/cdi/registry.go

This change reverts the NewCache function signature to also return an error. This was removed in #188 but does break clients such as moby using the NewCache API.
Instead, a private function is added that returns no error and this is used internally and in tests.

Revert NewCache function signature to return an error

---

cmd/cdi/cmd/cdi-api.go
cmd/cdi/cmd/monitor.go
cmd/cdi/cmd/root.go
pkg/cdi/default-cache.go
pkg/cdi/default-cache_test.go
pkg/cdi/doc.go
pkg/cdi/registry.go

This patch set
- reintroduces the implicitly available default cache
- adds a minimal set of package level functions (`Configure()`, `Refresh()`,` InjectDevices()`, `GetErrors()`) which use the default cache
- adds a `GetDefaultCache()` getter to allow other cache functions to be explicitly called on the default cache
- updates the registry to use the default cache instead of creating its own instance
- adds tests for the default cache
- adds a documentation note about future plans to obsolete and eventually remove  the registry abstraction
- update the `cdi` test utility to use the default cache

Implement default cache with a minimal set of package-level functions.

---

pkg/cdi/doc.go
pkg/cdi/registry.go

Mark Registry and its interfaces deprecated.

pkg/cdi: deprecate Registry and related interfaces.

---

.github/dependabot.yml
cmd/cdi/go.mod
cmd/cdi/go.sum
cmd/validate/go.sum
go.mod
go.sum
specs-go/go.mod
specs-go/go.sum

Since we are essenitally a library, we need to specify the MINIMUM version of the OCI runtime specification that we need. 
This change:
* Drops the required OCI runtime spec version in the CDI spec to v1.1.0 (where the `IntelRdt.EnableCMT` and `IntelRdt.EnableMBM` fields wer added).
* Removes the dependabot update for the OCI runtime spec.
closes #201

Decrease GitHub.com/opencontainers/runtime spec

---

pkg/cdi/container-edits.go
pkg/cdi/oci.go
specs-go/go.mod
specs-go/go.sum
specs-go/oci.go

This change removes the ToOCI functions from the specs-go package.
They are implemented as private toOCI functions in the cdi package instead.
This means that there is no dependency on the OCI runtime spec for clients that
only need a CDI spec definition.
**NOTE**: This is a breaking change in that the `ToOCI` functions no longer exist in the `specs-go` module, but the impact of this should be minimal and is worth the removal of the `require github.com/opencontainers/runtime-spec` dependency from the spec definitions.

Remove the ToOCI functions from the specs-go package

---

CONTRIBUTING.md

Add a section to the docs about community meetings and a pointer to the CNCF calendar with meeting details.

docs: add a pointer to community meetings in our docs.

---

SPEC.md
cmd/cdi/go.mod
go.mod
pkg/cdi/version.go
specs-go/config.go

This change bumps the CDI Spec version to v0.8.0. 
There were no spec-specific changes in the spec, but the version is being bumped due to there removal of the `.ToOCI()` functions from the spec types.

Bump spec version to v0.8.0

---

SPEC.md
specs-go/config.go

Document fields in spec to indicate when these were added.

---

.github/workflows/stale.yaml

Ignore issues / PRs with `lifecycle/frozen` label when marking them as stale / closing them.

Ignore issues / PRs with frozen labels for stale workflow

---

pkg/cdi/container-edits.go
pkg/cdi/validate/schema.go

Addresses inconsistent naming of imports, as reported in #227.

pkg/cdi: name cdi specs-go imports consistently.

---

cmd/cdi/cmd/cdi-api.go
pkg/cdi/cache_test.go
pkg/cdi/default-cache_test.go
pkg/cdi/spec-dirs_test.go

Fixed VSCode(gopls check) warnings:
```
$ find . -name \*.go | xargs gopls check
cmd/cdi/cmd/cdi-api.go:287:25-39: unused parameter: spec
cmd/cdi/cmd/cdi-api.go:287:41-53: unused parameter: verbose
pkg/cdi/spec-dirs_test.go:230:20-32: unused parameter: t [windows]
pkg/cdi/spec-dirs_test.go:230:20-32: unused parameter: t
pkg/cdi/spec-dirs_test.go:189:4: ineffectual assignment to err
```

Code cleanup

---

.github/workflows/golangci-lint.yml
Makefile
pkg/cdi/cache.go
pkg/cdi/default-cache_test.go

This patch set
- adds a local [golang]ci-lint Makefile target and hooks it in to pr-checks
- addresses golangci-lint complaints
- adds CI golangci-lint workflow

fixes: enable golanci-lint in CI, fix complaints.

---

SPEC.md

Document version match process

---

pkg/cdi/container-edits.go
pkg/cdi/container-edits_test.go

sortMounts stable and remove alphabetical order

---

.github/workflows/golangci-lint.yml
pkg/cdi/cache.go
pkg/cdi/cache_test_darwin.go
pkg/cdi/container-edits_test.go
pkg/cdi/spec.go

These changes fix running the unit tests on MacOS and make some minor golangci-lint changes.
The core of the problem is that file creation using `os.Rename` on `darwin` generates `CREATE` events and not `WRITE` events. This change also responds to CREATE events when updating the cache.

Fix cache refresh on darwin

---

.github/workflows/golangci-lint.yml
cmd/cdi/cmd/format.go
cmd/cdi/go.mod
cmd/cdi/go.sum
go.mod
go.sum
pkg/cdi/spec.go
schema/go.sum
specs-go/config.go

This closes #235 
A sample spec would now output as:
```
---
cdiVersion: v0.3.0
kind: example.com/class
devices: []
containerEdits:
deviceNodes:
- path: /dev/foo
```
instead of:
```
---
cdiVersion: v0.3.0
containerEdits:
deviceNodes:
- path: /dev/foo
devices: null
kind: example.com/class
```

Ensure that YAML fields are sorted

---

pkg/cdi/cache.go
pkg/cdi/cache_linux_test.go

Cherry picked #254 to release/0.8 branch.

[release/0.8] don't crash in cache refresh/update with nil fsnotify watcher.

---

RELEASE.md

These changes add a document listing the steps of the release process.
See the following PRs for version-bump changes:
* #257
* #211

Add RELEASE.md with steps to create a release

---

cmd/cdi/go.mod
cmd/validate/go.mod
schema/go.mod

Ref: https://github.com/cncf-tags/container-device-interface/issues/259

Bump version to v1.0.0

---

.github/ISSUE_TEMPLATE/new-release.md
RELEASE.md

This PR adds an issue template for tagging new releases. It uses the exact same process and format as the issue used for the `v1.0.0` release.
@elezar @bart0sh Should we add an issue template for new releases to the repository ?
@elezar If you already have it cooking somewhere, feel free to close this in favor of yours.

[RFC] .github: add issue template for releases.

---

.github/ISSUE_TEMPLATE/new-release.md

This change updates the release issue template to indicate that the specs.CurrentVersion should only be bumped if the spec is being udpated.

Only bump specs.CurrentVersion for spec updates

---

cmd/cdi/go.mod
cmd/validate/go.mod
schema/go.mod

This bumps the package version for the v1.0.1 release. There are no spec changes.
Requires #262 
Release is tracked in #263

Bump version to v1.0.1
